from pygame import USEREVENT

WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 500

CLOCK_TICK = 60
RADAR_RADIUS = 3000

NO_SPAWN_RADIUS = 150
INITIAL_ROCK_SPAWN_RATE = 5000
INITIAL_ENEMY_SPAWN_RATE = 500

ENEMY_SPAWN_EVENT = USEREVENT + 1
ROCK_SPAWN_EVENT = USEREVENT + 2
